# DICTIONARUL JOCULUI

# STATES
STATE_IDLE = "IDLE"
STATE_CHASE = "CHASE"
STATE_KICK = "KICK"
STATE_RESET = "RESET"
STATE_DO_THROW_IN = "DO_THROW_IN"
STATE_WAIT_THROW_IN = "WAIT_THROW_IN"
STATE_DRIBBLE = "DRIBBLE"
STATE_DRIBBLE_DUEL = "DRIBBLE_DUEL"
STATE_PASS = "PASS"
STATE_GK_DEFEND_GOAL = "GK_DEFEND_GOAL"
STATE_GK_CLEAR_BALL = "GK_CLEAR_BALL"
STATE_GK_HOLD_BALL = "GK_HOLD_BALL"


# STATUSES
STATUS_PLAYING = "PLAYING"
STATUS_GOAL = "GOAL"
STATUS_OUT = "OUT"
STATUS_START_GAME = "START_GAME"

# STARTING POSITIONS
STARTING_POSITIONS = {
    "1" : {"x": 0, "y": 50, "team": "A", "role": "GK"},
    "2" : {"x": 15, "y": 50, "team": "A", "role": "FIELD"},
    "101" : {"x": 70, "y": 80, "team":"B", "role": "FIELD"},
    "102" : {"x": 55, "y": 45, "team":"B", "role": "FIELD"},
}

# PLAYERS
NUM_OF_PLAYERS = 4