# DICTIONARUL JOCULUI

# STATES
STATE_IDLE = "IDLE"
STATE_CHASE = "CHASE"
STATE_KICK = "KICK"
STATE_RESET = "RESET"
STATE_DO_THROW_IN = "DO_THROW_IN"
STATE_WAIT_THROW_IN = "WAIT_THROW_IN"
STATE_DRIBBLE = "DRIBBLE"


# STATUSES
STATUS_PLAYING = "PLAYING"
STATUS_GOAL = "GOAL"
STATUS_OUT = "OUT"
STATUS_START_GAME = "START_GAME"

# STARTING POSITIONS
STARTING_POSITIONS = {
    "1" : {"x": 30, "y": 31},
    "2" : {"x": 60, "y": 50}
}

# PLAYERS
NUM_OF_PLAYERS = 2