# DICTIONARUL JOCULUI

# STATES
STATE_IDLE = "IDLE"
STATE_CHASE = "CHASE"
STATE_KICK = "KICK"
STATE_RESET = "RESET"
STATE_DO_THROW_IN = "DO_THROW_IN"
STATE_WAIT_THROW_IN = "WAIT_THROW_IN"


# STATUSES
STATUS_PLAYING = "PLAYING"
STATUS_GOAL = "GOAL"
STATUS_OUT = "OUT"